# Generated by Django 5.2.3 on 2025-06-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('population', models.BigIntegerField()),
                ('electrification_rate', models.FloatField(help_text='In percentage')),
                ('solar_potential', models.FloatField(help_text='Average solar irradiation (kWh/m²/day)')),
            ],
        ),
    ]
