# Generated by Django 5.2.3 on 2025-06-27 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statedata',
            options={'verbose_name': 'State Data', 'verbose_name_plural': 'States Data'},
        ),
    ]
