# Generated by Django 5.2.3 on 2025-07-24 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_statedata_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statedata',
            name='electrification_rate',
        ),
        migrations.RemoveField(
            model_name='statedata',
            name='solar_potential',
        ),
        migrations.AddField(
            model_name='statedata',
            name='boundary',
            field=models.JSONField(blank=True, help_text='GoeJSON boundary of the state', null=True),
        ),
        migrations.AddField(
            model_name='statedata',
            name='data_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='statedata',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DemographicData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poverty_rate', models.FloatField(blank=True, null=True)),
                ('mobile_ownership', models.FloatField(blank=True, null=True)),
                ('radio_ownership', models.FloatField(blank=True, null=True)),
                ('iron_sheet_roofing', models.FloatField(blank=True, null=True)),
                ('livestock_ownership', models.FloatField(blank=True, null=True)),
                ('household_electrification', models.FloatField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('data_source', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demographics', to='core.statedata')),
            ],
        ),
    ]
