# Generated by Django 5.2.3 on 2025-07-25 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_statedata_electrification_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialUseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_facilities', models.IntegerField(blank=True, help_text='Number of education facilities', null=True)),
                ('health_facilities', models.IntegerField(blank=True, help_text='Number of health facilities', null=True)),
                ('agricultural_zones', models.FloatField(blank=True, help_text='Agricultural land area or index', null=True)),
                ('mines_quarries', models.IntegerField(blank=True, help_text='Number of mines and quarries', null=True)),
                ('commercial_activities', models.IntegerField(blank=True, help_text='Estimated number of SMEs/commercial activities', null=True)),
                ('public_institutions', models.IntegerField(blank=True, help_text='Number of public institutions', null=True)),
                ('nighttime_lights', models.FloatField(blank=True, help_text='Average nighttime light intensity', null=True)),
                ('year', models.IntegerField()),
                ('data_source', models.CharField(max_length=255)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_uses', to='core.statedata')),
            ],
        ),
    ]
