# Generated by Django 5.2.3 on 2025-07-26 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_socialusedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solar_potential', models.FloatField(blank=True, help_text='Average solar irradiation (kWh/m2/day)', null=True)),
                ('wind_potential', models.FloatField(blank=True, help_text='Average wind speed (m/s)', null=True)),
                ('biomass_potential', models.FloatField(blank=True, help_text='Biomass potential (tons/year or GWh)', null=True)),
                ('hydro_potential', models.FloatField(blank=True, help_text='Small/medium hydro potential (MW)', null=True)),
                ('year', models.IntegerField()),
                ('data_source', models.CharField(max_length=255)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='core.statedata')),
            ],
        ),
    ]
