# Generated by Django 5.2.3 on 2025-07-26 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_resourcedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfrastructureData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transmission_lines_km', models.FloatField(blank=True, help_text='Length of transmission lines (km)', null=True)),
                ('substations_count', models.IntegerField(blank=True, help_text='Number of substations', null=True)),
                ('mini_grids_count', models.IntegerField(blank=True, help_text='Number of operational mini-grids', null=True)),
                ('off_grid_solutions', models.IntegerField(blank=True, help_text='Number of off-grid installations (SHS, community systems)', null=True)),
                ('power_plants_count', models.IntegerField(blank=True, help_text='Number of power plants', null=True)),
                ('accessibility_to_cities', models.FloatField(blank=True, help_text='Average travel time to nearest city (minutes)', null=True)),
                ('year', models.IntegerField()),
                ('data_source', models.CharField(max_length=255)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infrastructures', to='core.statedata')),
            ],
        ),
    ]
