# Generated by Django 5.2.3 on 2025-07-28 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_infrastructuredata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrastructuredata',
            name='state',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='infrastructures', to='core.statedata'),
        ),
        migrations.AlterField(
            model_name='resourcedata',
            name='state',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='core.statedata'),
        ),
        migrations.AlterField(
            model_name='socialusedata',
            name='state',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_uses', to='core.statedata'),
        ),
        migrations.CreateModel(
            name='DemographicsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poverty_rate', models.FloatField(blank=True, null=True)),
                ('mobile_ownership', models.FloatField(blank=True, null=True)),
                ('radio_ownership', models.FloatField(blank=True, null=True)),
                ('iron_sheet_roofing', models.FloatField(blank=True, null=True)),
                ('livestock_ownership', models.FloatField(blank=True, null=True)),
                ('household_electrification', models.FloatField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('data_source', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demographics', to='core.statedata')),
            ],
        ),
        migrations.DeleteModel(
            name='DemographicData',
        ),
    ]
