# Generated by Django 5.2.3 on 2025-07-28 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_infrastructuredata_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrastructuredata',
            name='state',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='infrastructure', to='core.statedata'),
        ),
    ]
